/// Flutter icons Integron
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Integron
///      fonts:
///       - asset: fonts/Integron.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Integron {
  Integron._();

  static const _kFontFam = 'Integron';
  static const _kFontPkg = null;

  static const IconData help_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_f = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vk = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData integron = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
